name: Rust
on:
  push:
    branches: [ main ]
    paths:
      - 'rust/**'
      - '.github/workflows/rust.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'rust/**'
      - '.github/workflows/rust.yml'

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-rust-rustfmt
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
        working-directory: rust

  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-rust-build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --verbose
        working-directory: rust
      - run: cargo test --verbose
        working-directory: rust
